ECommerce/ECommerce/urls.py
from . import views
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from products.views import ProductListView



urlpatterns = [
    path('', ProductListView.as_view(), name='index'),#call the def after go to the url '' to give show the response
    path('users/login', views.login_view, name='login'),
    path('users/signup', views.signup, name='signup'),
    path('users/logout', views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('cart/', include('carts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ECommerce/carts/urls.py
from .import views
from django.urls import path
app_name = 'cart'
#por esto uso url 'cart:add', url 'cart:remove' etc etc

urlpatterns = [
    path('',views.cart, name='cart'),
    path('add', views.add, name='add'),
    path('remove', views.remove, name='remove')
]

ECommerce/products/urls.py
from . import views
from django.urls import path


app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product')
]

ECommerce/products/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank= False, unique= True)
    image = models.ImageField(upload_to='products/', null = False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        
        while Product.objects.filter(slug = slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4()) [:8])
            )
        
        instance.slug = slug

pre_save.connect(set_slug, sender=Product )

ECommerce/products/views.py
from typing import Any
from .models import Product
from django.db.models import  Q
from django.shortcuts import render
from django.db.models.query import QuerySet
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# Create your views here.

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context['message'] = 'Lista de productos'
         return context
    
class ProductDetailView(DetailView):
     model = Product
     template_name = 'products/product.html'

     
class ProductSearchListView(ListView):
     template_name= 'products/search.html'

     def get_queryset(self):
          filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
          return Product.objects.filter(filters)
     
     def query(self):
          return self.request.GET.get('q')
     
     def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context['query'] = self.query()
         context['count'] = context['product_list'].count()
         return context

ECommerce/products/templates/products/snippets/list.html
<div class="row ml-auto mr-auto">
    {% for object in product_list %}
        <div class="col-4 mt-5">
            {% include 'products/snippets/product.html' with product=object %}
        </div>
    {% endfor %}
</div>

ECommerce/products/templates/products/snippets/product.html
<div class="card h-500">

    <div class="text-center mt-2">
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="Imagen del producto" width="300" height="400" class="rounded">
        {% endif %}
    </div>

    <div class="card-body">
        <h5 class="card-title">{{ product.title }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <a href="{% url 'products:product' product.slug  %}" class="btn btn-primary">Ver más</a>
    </div>

</div>

ECommerce/products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-primary">
        </div>
    </div>
</form>